# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwt < Formula
  desc ""
  homepage "https://github.com/duckhue01/jwt"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/duckhue01/jwt/releases/download/v0.3.0/jwt_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f604c635798e00f2aa145e11a8168bb970d98e06ca1cc033e52062814e18999b"

      def install
        bin.install "jwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/duckhue01/jwt/releases/download/v0.3.0/jwt_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "96d6442e8508535ee1d98413db494ed3c5fca920288228d38286f53d1f8e4522"

      def install
        bin.install "jwt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duckhue01/jwt/releases/download/v0.3.0/jwt_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9b557f32833c0b3eef861cdb9c06cdd0834ade6d6d46e23d6c4f6dcea1bf9e27"

      def install
        bin.install "jwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/duckhue01/jwt/releases/download/v0.3.0/jwt_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "9b77488db7b0f54209b2f03f97f7e14dde620e7aef7ff0baee1f6442f2a62525"

      def install
        bin.install "jwt"
      end
    end
  end
end
