# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwt < Formula
  desc ""
  homepage "https://github.com/duckhue01/jwt"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/duckhue01/jwt/releases/download/v0.1.0/jwt_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "cb394a49e5a35d3158775c006e61880ff24c81c8f4c6f3dcb6027acc36c6b04a"

      def install
        bin.install "jwt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/duckhue01/jwt/releases/download/v0.1.0/jwt_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "01b3af7984c60115db04a3660ecfe4ca27ac39bfbf5aafd552c8e572d4a8d415"

      def install
        bin.install "jwt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duckhue01/jwt/releases/download/v0.1.0/jwt_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f244337e3006628c0f33a36e9bb3cc6c202f7e98f771d97bae88583c5da83c64"

      def install
        bin.install "jwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/duckhue01/jwt/releases/download/v0.1.0/jwt_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "62affc4c52f54bbd11d97dd9c9c540537c0611cd7ceaa14198b2deea35b2dc40"

      def install
        bin.install "jwt"
      end
    end
  end
end
